
insert into variable_entity (default_data) values ('deafult product/service');
insert into warehouse (name, address) values ('deafult warehouse', 'city');
insert into stock (instock, warehouseID, variableentityID) values (0, 1, 1);
insert into rol (name) values ('super');
insert into rol (name) values ('admin');
insert into rol (name) values ('shopkeeper');
insert into rol (name) values ('Warehouse manager');
insert into rol (name) values ('delivery man');
insert into permission (name) values ('god');
insert into permission (name) values ('report view');
insert into permission (name) values ('shop managment');
insert into permission (name) values ('Warehouse managment');
insert into permission (name) values ('deliver');
insert into role_permission (rolID, permissionID) values (1, 1);
insert into role_permission (rolID, permissionID) values (1, 2);
insert into role_permission (rolID, permissionID) values (1, 3);
insert into role_permission (rolID, permissionID) values (1, 4);
insert into role_permission (rolID, permissionID) values (1, 5);
insert into role_permission (rolID, permissionID) values (2, 1);
insert into role_permission (rolID, permissionID) values (2, 2);
insert into role_permission (rolID, permissionID) values (2, 3);
insert into role_permission (rolID, permissionID) values (2, 4);
insert into role_permission (rolID, permissionID) values (2, 5);
insert into role_permission (rolID, permissionID) values (3, 3);
insert into role_permission (rolID, permissionID) values (4, 4);
insert into role_permission (rolID, permissionID) values (5, 5);
insert into store (name, address) values ('store one', 'city');
insert into user (user, password, rolID, storeID) values ('cindy', 'e40bbc044c5f9566ac701839fb87615e', 1 ,1);
insert into payment_type (name) values ('cash');
insert into client (name, NIT, phonenumber, email, address) values ('Final consumer', 'C/F', '', '', '');